/*
	This code is my attempt to create a QM simplifier system in JS...
	A system that would generate a simplified expression given a truth table(in the form of minterms)

	This file contains an implementation for a MULTI-variable 'online' QM system...

	author: @yash.diniz;
*/

//TODO: Try to work your brain on this one...

//Until then, workaround: Multi variable expression(In Expression.js). Allows to return a byte of data...